{
 "title": "Node Operators",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module_var",
    "label": "Module",
    "query": {
     "query": "label_values(ethereum_validators_monitoring_user_validators, nos_module_id)"
    }
   },
   {
    "name": "nos_name_var",
    "label": "Node Operator",
    "query": {
     "query": "query_result(last_over_time(ethereum_validators_monitoring_user_validators{nos_module_id=~'${module_var}'}[28h]))"
    }
   },
   { "name": "show_dvts_var", "label": "Show related clusters", "query": "Yes : 1, No : -1" },
   {
    "name": "epoch_number_var",
    "label": "Epoch number",
    "query": {
     "query": "query_result(last_over_time(ethereum_validators_monitoring_epoch_number[28h]))"
    }
   },
   {
    "name": "sync_participation_distance_var",
    "label": "Sync participation distance down from chain average",
    "query": {
     "query": "query_result(last_over_time(ethereum_validators_monitoring_sync_participation_distance_down_from_chain_avg[28h]))"
    }
   },
   { "name": "limit", "label": "Row limit", "query": "100" },
   {
    "name": "att_epochs_var",
    "query": {
     "query": "label_values(ethereum_validators_monitoring_validator_count_miss_attestation_last_n_epoch, epoch_interval)"
    }
   },
   {
    "name": "sync_epochs_var",
    "query": {
     "query": "label_values(ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg_last_n_epoch, epoch_interval)"
    }
   },
   {
    "name": "chain_sync_avg_participation",
    "label": "Chain sync participation average",
    "query": {
     "query": "query_result(last_over_time(ethereum_validators_monitoring_chain_sync_participation_avg_percent[28h]))"
    }
   },
   {
    "name": "epochs_range",
    "label": "Epochs range",
    "query": {
     "query": "query_result(sum_over_time((changes(sum(ethereum_validators_monitoring_epoch_number)[25s:]) > 0)[$__range:]))"
    }
   },
   {
    "name": "nos_global_index_var",
    "label": "Node Operator Global Indexes",
    "query": {
     "query": "query_result(label_join(last_over_time(ethereum_validators_monitoring_user_validators{nos_module_id=~'${module_var}', nos_name='${nos_name_var}'}[28h]), 'nos_global_index', ';', 'nos_module_id', 'nos_id'))"
    }
   },
   {
    "name": "dvt_nos_global_indexes_var",
    "label": "Related DVT Operators Global Indexes",
    "query": {
     "query": "query_result(last_over_time(operators_indexes_map{main_global_index=~'${nos_global_index_var}'}[28h]) == ${show_dvts_var})"
    }
   },
   {
    "name": "mapped_nos_names_var",
    "label": "Node Operator and Related DVT Clusters",
    "query": {
     "query": "query_result(last_over_time(ethereum_validators_monitoring_user_operators_identifies{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}[28h]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data actuality",
   "type": "stat",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)"
    }
   ]
  },
  {
   "title": "Data actuality x Epoch",
   "type": "timeseries",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)",
     "legendFormat": "Data actuality"
    },
    {
     "expr": "ethereum_validators_monitoring_epoch_number",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Node operator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_name) (ethereum_validators_monitoring_user_validators{nos_name=~'${mapped_nos_names_var}'})",
     "legendFormat": "🏖️  {{nos_name}}"
    }
   ]
  },
  {
   "title": "Unmonitored keys",
   "type": "stat",
   "description": "Number of unmonitored (stuck) keys that are defined manually. Such keys will not be taken into account when calculating validator metrics and alerts",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='stuck', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Last processed for a specified time period",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_epoch_number)"
    }
   ]
  },
  { "title": "🏠 General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ongoing validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='ongoing', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Pending validators",
   "type": "stat",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='pending', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawal pending",
   "type": "stat",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_pending', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawn",
   "type": "stat",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_done', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Slashed validators",
   "type": "stat",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='slashed', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Ongoing validators share",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='ongoing', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='ongoing', nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Pending validators share",
   "type": "piechart",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='pending', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='pending', nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Full withdrawal pending",
   "type": "piechart",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_pending', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_pending', nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Full withdrawn",
   "type": "piechart",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_done', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='withdrawal_done', nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Slashed validators share",
   "type": "piechart",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='slashed', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_user_validators{status='slashed', nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Status progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (status) (ethereum_validators_monitoring_user_validators{status=~'ongoing|pending|withdrawal_pending|withdrawal_done', nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "On exit validators",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator,\n  val_status AS Status,\n  val_balance / pow(10,9) AS Balance\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  val_status IN ['active_exiting','exited_unslashed', 'exited_slashed', 'withdrawal_possible'] AND\n  val_balance != 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id, val_balance\nLIMIT 1 BY val_id",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator,\n  val_status AS Status,\n  val_balance / pow(10,9) AS Balance\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  val_status IN ['active_exiting','exited_unslashed', 'exited_slashed', 'withdrawal_possible'] AND\n  val_balance != 0 AND\n  epoch = 222117\nORDER BY val_id, val_balance\nLIMIT 1 BY val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total withdrawals count by type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (type) (ethereum_validators_monitoring_operator_withdrawals_count{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "💔 Alerting only (at incident time range)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Negative balance delta",
   "type": "table",
   "description": "Delta: current slot - 192 slot",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  current.val_nos_module_id AS Module,\n  current.val_nos_name AS Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id AS Validator\nFROM (\n  SELECT\n    val_balance,\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_slashed,\n    val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = ${epoch_number_var}\n  LIMIT 1 BY val_id\n) AS current\nINNER JOIN (\n  SELECT val_balance, val_id\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = ${epoch_number_var} - 6\n  LIMIT 1 BY val_id\n) AS previous\nON\n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) AS withdrawn,\n    val_id,\n    val_nos_module_id,\n    val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_module_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_balance_withdrawn > 0 AND\n      val_stuck = 0 AND\n      (${epoch_number_var} - 6) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_id = current.val_id\nHAVING (current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0)) < 0 AND current.val_slashed = 0\nORDER BY GWei ASC, Validator\nLIMIT CAST(${limit}, 'Int16')",
     "rawQuery": "SELECT\n  current.val_nos_module_id AS Module,\n  current.val_nos_name AS Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id AS Validator\nFROM (\n  SELECT\n    val_balance,\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_slashed,\n    val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = 222126\n  LIMIT 1 BY val_id\n) AS current\nINNER JOIN (\n  SELECT val_balance, val_id\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = 222126 - 6\n  LIMIT 1 BY val_id\n) AS previous\nON\n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) AS withdrawn,\n    val_id,\n    val_nos_module_id,\n    val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_module_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_balance_withdrawn > 0 AND\n      val_stuck = 0 AND\n      (222126 - 6) < epoch AND epoch <= 222126\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_id = current.val_id\nHAVING (current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0)) < 0 AND current.val_slashed = 0\nORDER BY GWei ASC, Validator\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Missed proposals",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  block_to_propose AS Block,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 BY val_id",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  block_to_propose AS Block,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  epoch = 222135\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 BY val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bad Sync participation (${sync_epochs_var} epochs in a row)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_nos_module_id,\n    val_nos_id,\n    val_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT\n      val_id,\n      val_nos_module_id,\n      val_nos_id,\n      val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      is_sync = 1 AND\n      val_stuck = 0 AND\n      sync_percent < (${chain_sync_avg_participation} - ${sync_participation_distance_var}) AND\n      (${epoch_number_var} - ${sync_epochs_var}) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = ${sync_epochs_var}\nORDER BY count_fail DESC, val_id",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_nos_module_id,\n    val_nos_id,\n    val_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT\n      val_id,\n      val_nos_module_id,\n      val_nos_id,\n      val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      is_sync = 1 AND\n      val_stuck = 0 AND\n      sync_percent < (99.200439453125 - 0) AND\n      (222137 - 3) < epoch AND epoch <= 222137\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Missed attestation (${att_epochs_var} epochs in a row)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      att_happened = 0 AND\n      val_stuck = 0 AND\n      (${epoch_number_var} - ${att_epochs_var}) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT CAST(${limit}, 'Int16')",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      att_happened = 0 AND\n      val_stuck = 0 AND\n      (222140 - 3) < epoch AND epoch <= 222140\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High inclusion delay (${att_epochs_var} epochs in a row)",
   "type": "table",
   "description": "inclusion delay > 1",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      att_happened = 1 AND\n      att_inc_delay > 1 AND\n      val_stuck = 0 AND\n      (${epoch_number_var} - ${att_epochs_var}) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT CAST(${limit}, 'Int16')",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      att_happened = 1 AND\n      att_inc_delay > 1 AND\n      val_stuck = 0 AND\n      (222142 - 3) < epoch AND epoch <= 222142\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Two invalid attestation properties (${att_epochs_var} epochs in a row)",
   "type": "table",
   "description": "Validators that have two invalid attestation properties (head or target or source) in the last ${att_epochs_var} epochs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      att_valid_head + att_valid_target + att_valid_source = 1 AND\n      val_stuck = 0 AND\n      (${epoch_number_var} - ${att_epochs_var}) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT CAST(${limit}, 'Int16')",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_module_id, val_nos_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      att_valid_head + att_valid_target + att_valid_source = 1 AND\n      val_stuck = 0 AND\n      (222147 - 3) < epoch AND epoch <= 222147\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Slashed",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_status AS Status,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  (val_status = 'active_slashed' OR val_status = 'exited_slashed' OR val_slashed = 1) AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id",
     "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_status AS Status,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  (val_status = 'active_slashed' OR val_status = 'exited_slashed' OR val_slashed = 1) AND\n  epoch = 222149\nORDER BY val_id\nLIMIT 1 BY val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "💸 Balances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator balance 24h delta",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "(sum by (nos_name) (ethereum_validators_monitoring_operator_balance_24h_difference{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) / 10 ^ 9) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Average validator balances delta",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balances_delta{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Worst validator balances delta [0.1% percentile]",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_quantile_001_balances_delta{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Validators with worst balance delta",
     "type": "table",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 87 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  current.val_nos_module_id AS Module,\n  current.val_nos_name AS Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id AS Validator\nFROM (\n  SELECT\n    val_balance,\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = ${epoch_number_var}\n  LIMIT 1 BY val_id\n) AS current\nINNER JOIN (\n  SELECT val_balance, val_id\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = ${epoch_number_var} - 6\n  LIMIT 1 BY val_id\n) AS previous\nON\n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) AS withdrawn,\n    val_id,\n    val_nos_module_id,\n    val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_module_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n      val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_balance_withdrawn > 0 AND\n      val_stuck = 0 AND\n      (${epoch_number_var} - 6) < epoch AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Validator\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  current.val_nos_module_id AS Module,\n  current.val_nos_name AS Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id AS Validator\nFROM (\n  SELECT\n    val_balance,\n    val_id,\n    val_nos_module_id,\n    val_nos_id,\n    val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = 222150\n  LIMIT 1 BY val_id\n) AS current\nINNER JOIN (\n  SELECT val_balance, val_id\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n    val_stuck = 0 AND\n    epoch = 222150 - 6\n  LIMIT 1 BY val_id\n) AS previous\nON\n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) AS withdrawn,\n    val_id,\n    val_nos_module_id,\n    val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_module_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_status IN ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_balance_withdrawn > 0 AND\n      val_stuck = 0 AND\n      (222150 - 6) < epoch AND epoch <= 222150\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_module_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Validator\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with negative delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_negative_balances_delta{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    }
   ]
  },
  {
   "title": "📥 Proposals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed proposals (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  block_to_propose AS Block,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  (${epoch_number_var} - ${epochs_range}) < epoch AND epoch <= ${epoch_number_var}\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 BY epoch, val_id",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  block_to_propose AS Block,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  (222157 - 19) < epoch AND epoch <= 222157\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 BY epoch, val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with missed proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 77 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_propose{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    }
   ]
  },
  {
   "title": "🔄 Sync Committee participation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "${nos_name_var} vs Other",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_other_sync_participation_avg_percent) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "Rest of chain"
      },
      {
       "expr": "avg(ethereum_validators_monitoring_operator_sync_participation_avg_percent{nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'} AND ON(nos_name) (ethereum_validators_monitoring_validator_count_with_good_sync_participation{nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'} + ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_global_index!~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'} > 0) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0) ",
       "legendFormat": "Rest of User's"
      },
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_operator_sync_participation_avg_percent{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON(nos_name) (ethereum_validators_monitoring_validator_count_with_good_sync_participation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'} + ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'} > 0) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Bad Sync Committee participation",
     "type": "table",
     "description": "AVERAGE.\n`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  sync_percent AS Percent,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  is_sync = 1 AND\n  val_stuck = 0 AND\n  sync_percent < (${chain_sync_avg_participation} - ${sync_participation_distance_var}) AND\n  epoch = ${epoch_number_var}\nORDER BY sync_percent, val_id\nLIMIT 1 BY val_id",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  sync_percent AS Percent,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  is_sync = 1 AND\n  val_stuck = 0 AND\n  sync_percent < (99.0234375 - 0) AND\n  epoch = 222160\nORDER BY sync_percent, val_id\nLIMIT 1 BY val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with sync participation less average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 84 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "📝 Attestations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validators with MISSED attestation",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  att_happened = 0 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  att_happened = 0 AND\n  val_stuck = 0 AND\n  epoch = 222164\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with MISSED attestation",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_attestation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with high INCLUSION DELAY attestation",
     "type": "table",
     "description": "inclusion delay > 1",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  att_happened = 1 AND\n  att_inc_delay > 1 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  att_happened = 1 AND\n  att_inc_delay > 1 AND\n  val_stuck = 0 AND\n  epoch = 222165\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with high attestation INCLUSION DELAY",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 87 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}', reason='high_inclusion_delay'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid HEAD",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  att_valid_head = 0 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  att_valid_head = 0 AND\n  val_stuck = 0 AND\n  epoch = 222169\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation HEAD",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 95 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}', reason='invalid_head'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid TARGET",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  att_valid_target = 0 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  att_valid_target = 0 AND\n  val_stuck = 0 AND\n  epoch = 222158\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation TARGET",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 103 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}', reason='invalid_target'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validator with invalid SOURCE",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries AS t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat([${nos_global_index_var}], splitByChar('|','${dvt_nos_global_indexes_var:pipe}')) AND\n  att_valid_source = 0 AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT CAST(${limit}, 'Int16')",
       "rawQuery": "SELECT\n  val_nos_module_id AS Module,\n  val_nos_name AS Operator,\n  val_id AS Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  att_valid_source = 0 AND\n  val_stuck = 0 AND\n  epoch = 222171\nORDER BY val_id\nLIMIT 1 BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation SOURCE",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var:pipe}', reason='invalid_source'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🧲 Consolidations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consolidating source validators share (amount)",
     "type": "piechart",
     "description": "Number of validators with `source_index` belonging to ${nos_name_var} in pending consolidation queue in comparison with total number of User validator `source_index`es in the queue belonging to other User operators",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_count{type=\"source\",nos_name=~\"${nos_name_var}\"})",
       "legendFormat": "${nos_name_var}"
      },
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_count{type=\"source\",nos_name!~\"${nos_name_var}\"})",
       "legendFormat": "Other User operators"
      }
     ]
    },
    {
     "title": "Number of User validators initiating consolidation",
     "type": "timeseries",
     "description": "Number of validators with `source_index` belonging to ${nos_name_var} in pending consolidation queue",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_consolidation_count{type=\"source\", nos_name=~'${nos_name_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Consolidating source validators share (balance)",
     "type": "piechart",
     "description": "Total balance of validators with `source_index` belonging to ${nos_name_var} in pending consolidation queue in comparison with total balance of User validator `source_index`es in the queue belonging to other User operators",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_balance{type=\"source\",nos_name=~\"${nos_name_var}\"}) / 10^4",
       "legendFormat": "${nos_name_var} (ETH)"
      },
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_balance{type=\"source\",nos_name!~\"${nos_name_var}\"}) / 10^4",
       "legendFormat": "Other User operators (ETH)"
      }
     ]
    },
    {
     "title": "Total balance of User validators initiating consolidation (in ETH)",
     "type": "timeseries",
     "description": "Total balance of validators with `source_index` belonging to ${nos_name_var} in pending consolidation queue (in ETH)",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_consolidation_balance{type=\"source\", nos_name=~'${nos_name_var}'} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Consolidating target validators share (amount)",
     "type": "piechart",
     "description": "Number of validators with `target_index` belonging to ${nos_name_var} in pending consolidation queue in comparison with total number of User validator `target_index`es in the queue belonging to other User operators",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_count{type=\"target\",nos_name=~\"${nos_name_var}\"})",
       "legendFormat": "${nos_name_var}"
      },
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_count{type=\"target\",nos_name!~\"${nos_name_var}\"})",
       "legendFormat": "Other User operators"
      }
     ]
    },
    {
     "title": "Number of User target consolidation validators",
     "type": "timeseries",
     "description": "Number of validators with `target_index` belonging to ${nos_name_var} in pending consolidation queue",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_consolidation_count{type=\"target\", nos_name=~'${nos_name_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Consolidating target validators share (balance)",
     "type": "piechart",
     "description": "Total balance of validators with `target_index` belonging to ${nos_name_var} in pending consolidation queue in comparison with total balance of User validator `target_index`es in the queue belonging to other User operators",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_balance{type=\"target\",nos_name=~\"${nos_name_var}\"}) / 10^4",
       "legendFormat": "${nos_name_var} (ETH)"
      },
      {
       "expr": "sum(ethereum_validators_monitoring_validator_consolidation_balance{type=\"target\",nos_name!~\"${nos_name_var}\"}) / 10^4",
       "legendFormat": "Other User operators (ETH)"
      }
     ]
    },
    {
     "title": "Total balance of User target consolidation validators (in ETH)",
     "type": "timeseries",
     "description": "Total balance of validators with `target_index` belonging to ${nos_name_var} in pending consolidation queue (in ETH)",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_consolidation_balance{type=\"target\", nos_name=~'${nos_name_var}'} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  }
 ]
}