{
 "title": "Validators",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "epoch_number_var",
    "label": "Epoch number",
    "query": {
     "query": "query_result(ethereum_validators_monitoring_epoch_number)"
    }
   },
   {
    "name": "sync_participation_distance_var",
    "label": "Sync participation distance down from chain average",
    "query": {
     "query": "query_result(ethereum_validators_monitoring_sync_participation_distance_down_from_chain_avg)"
    }
   },
   {
    "name": "chain_sync_avg_participation",
    "label": "Chain sync participation average",
    "query": {
     "query": "query_result(ethereum_validators_monitoring_chain_sync_participation_avg_percent)"
    }
   },
   {
    "name": "epochs_range",
    "label": "Epochs range",
    "query": {
     "query": "query_result(sum_over_time((changes(sum(ethereum_validators_monitoring_epoch_number)[25s:]) > 0)[$__range:]))"
    }
   },
   {
    "name": "module_var",
    "label": "Module",
    "query": {
     "query": "label_values(ethereum_validators_monitoring_validators,nos_module_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data actuality",
   "type": "stat",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)"
    }
   ]
  },
  {
   "title": "Data actuality x Epoch",
   "type": "timeseries",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)",
     "legendFormat": "Data actuality"
    },
    {
     "expr": "ethereum_validators_monitoring_epoch_number",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Unmonitored keys",
   "type": "stat",
   "description": "Number of unmonitored (stuck) keys that are defined manually. Such keys will not be taken into account when calculating validator metrics and alerts",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"stuck\"})"
    }
   ]
  },
  {
   "title": "Unmonitored keys balance",
   "type": "stat",
   "description": "Total balance of unmonitored (stuck) keys that are defined manually. Such keys will not be taken into account when calculating validator metrics and alerts",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"stuck\"} / 10^4))"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Last processed for a specified time period",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_epoch_number)"
    }
   ]
  },
  { "title": "🏠 General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ongoing User Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ethereum_validators_monitoring_validators{owner=\"user\",status=\"ongoing\", nos_module_id=\"$module_var\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Pending User Validators",
   "type": "stat",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"pending\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawal pending User Validators",
   "type": "stat",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_pending\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawn User Validators",
   "type": "stat",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_done\",nos_module_id=\"${module_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Slashed User Validators",
   "type": "stat",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"slashed\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Ongoing User Validators Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"ongoing\", nos_module_id=\"$module_var\"} / 10^4))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Pending User Validators Balance",
   "type": "stat",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"pending\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawal pending User Validators Balance",
   "type": "stat",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"withdrawal_pending\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawn User Validators Balance",
   "type": "stat",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"withdrawal_done\",nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Slashed User Validators Balance",
   "type": "stat",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"slashed\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Ongoing Validators",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_module_id) (ethereum_validators_monitoring_validators{owner=\"user\",status=\"ongoing\", nos_module_id=~\"${module_var}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"ongoing\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Pending Validators",
   "type": "piechart",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_module_id) (ethereum_validators_monitoring_validators{owner=\"user\",status=\"pending\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"pending\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Full withdrawal pending Validators",
   "type": "piechart",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_module_id) (ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_pending\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"withdrawal_pending\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Full withdrawn Validators",
   "type": "piechart",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_module_id) (ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_done\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"withdrawal_done\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "piechart",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_module_id) (ethereum_validators_monitoring_validators{owner=\"user\",status=\"slashed\", nos_module_id=\"${module_var}\"})",
     "legendFormat": "User"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"slashed\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Ongoing Validators Balance",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (nos_module_id) (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"ongoing\", nos_module_id=~\"${module_var}\"} / 10^4))",
     "legendFormat": "User (ETH)"
    },
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"other\",status=\"ongoing\"} / 10^4))",
     "legendFormat": "Other (ETH)"
    }
   ]
  },
  {
   "title": "Pending Validators Balance",
   "type": "piechart",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (nos_module_id) (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"pending\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "User (ETH)"
    },
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"other\",status=\"pending\"} / 10^4))",
     "legendFormat": "Other (ETH)"
    }
   ]
  },
  {
   "title": "Full withdrawal pending Validators Balance",
   "type": "piechart",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (nos_module_id) (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"withdrawal_pending\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "User (ETH)"
    },
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"other\",status=\"withdrawal_pending\"} / 10^4))",
     "legendFormat": "Other (ETH)"
    }
   ]
  },
  {
   "title": "Full withdrawn Validators Balance",
   "type": "piechart",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (nos_module_id) (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"withdrawal_done\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "User (ETH)"
    },
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"other\",status=\"withdrawal_done\"} / 10^4))",
     "legendFormat": "Other (ETH)"
    }
   ]
  },
  {
   "title": "Slashed Validators Balance",
   "type": "piechart",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (nos_module_id) (ethereum_validators_monitoring_validators_balance{owner=\"user\",status=\"slashed\", nos_module_id=\"${module_var}\"} / 10^4))",
     "legendFormat": "User (ETH)"
    },
    {
     "expr": "round(sum(ethereum_validators_monitoring_validators_balance{owner=\"other\",status=\"slashed\"} / 10^4))",
     "legendFormat": "Other (ETH)"
    }
   ]
  },
  {
   "title": "Operator Statuses",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (nos_name, status, nos_module_id) (ethereum_validators_monitoring_user_validators{status=~\"ongoing|pending|withdrawal_pending|withdrawal_done\", nos_module_id=\"${module_var}\"}))"
    }
   ]
  },
  {
   "title": "Total Status progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (status) (ethereum_validators_monitoring_user_validators{status=~\"ongoing|pending|withdrawal_pending|withdrawal_done\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "ETH per Operator Statuses",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (nos_name, status, nos_module_id) (ethereum_validators_monitoring_user_validators_balance{status=~\"ongoing|pending|withdrawal_pending|withdrawal_done\", nos_module_id=\"${module_var}\"} / 10^4))"
    }
   ]
  },
  {
   "title": "Total Status progress (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (status) (ethereum_validators_monitoring_user_validators_balance{status=~\"ongoing|pending|withdrawal_pending|withdrawal_done\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total withdrawals count by type",
   "type": "timeseries",
   "description": "A validator is considered `fully` withdrawn if it has withdrawn a balance in a certain epoch and its balance is 0,  otherwise it is considered `partially` withdrawn",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (type) (ethereum_validators_monitoring_operator_withdrawals_count{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Withdrawal pending User validators",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    val_id as Validator,\n    val_nos_name as Operator,\n    val_status as Status,\n    val_balance / pow(10,9) as Balance\nFROM\n    validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  val_nos_name is not NULL AND\n  epoch = ${epoch_number_var} AND\n  (val_status in ['active_exiting','exited_unslashed', 'exited_slashed'] or val_status == 'withdrawal_possible' and val_balance != 0)\nORDER BY val_id, val_balance\nLIMIT 1 by val_id",
     "rawQuery": "SELECT\n    val_id as Validator,\n    val_nos_name as Operator,\n    val_status as Status,\n    val_balance / pow(10,9) as Balance\nFROM\n    validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  val_nos_name is not NULL AND\n  epoch = 216244 AND\n  (val_status in ['active_exiting','exited_unslashed', 'exited_slashed'] or val_status == 'withdrawal_possible' and val_balance != 0)\nORDER BY val_id, val_balance\nLIMIT 1 by val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "📒 Performance summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Propose (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_miss_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_good_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Other Propose (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_miss_propose) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_good_propose) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Propose summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_good_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_good_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Propose sharing (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_miss_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_good_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_miss_propose) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_good_propose) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "User Sync (${epochs_range} epochs range)",
     "type": "piechart",
     "description": "`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_with_good_sync_participation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Other Sync (${epochs_range} epochs range)",
     "type": "piechart",
     "description": "`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_with_sync_participation_less_avg) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_with_good_sync_participation) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Sync summary (${epochs_range} epochs range)",
     "type": "table",
     "description": "`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`)",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_good_sync_participation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_with_good_sync_participation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "avg_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_sync_participation_avg_percent{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "User Sync (${epochs_range} epochs range, ETH)",
     "type": "piechart",
     "description": "`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_with_good_sync_participation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Other Sync (${epochs_range} epochs range, ETH)",
     "type": "piechart",
     "description": "`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_with_sync_participation_less_avg / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_with_good_sync_participation / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Sync sharing (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_with_good_sync_participation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_with_sync_participation_less_avg) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_with_good_sync_participation) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Sync sharing (${epochs_range} epochs range, ETH)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_with_good_sync_participation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_with_sync_participation_less_avg / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) + sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_with_good_sync_participation / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "User Attestation (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_perfect_attestation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_miss_attestation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_target\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_source\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Attestation duty summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_perfect_attestation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_perfect_attestation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_attestation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_miss_attestation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_target\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_target\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_source\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_source\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "User Attestation (${epochs_range} epochs range, ETH)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_perfect_attestation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_miss_attestation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_target\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_source\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Other Attestation (${epochs_range} epochs range)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_perfect_attestation) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_miss_attestation) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_invalid_attestation{reason=\"high_inclusion_delay\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_invalid_attestation{reason=\"invalid_head\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_invalid_attestation{reason=\"invalid_target\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_count_invalid_attestation{reason=\"invalid_source\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Other Attestation (${epochs_range} epochs range, ETH)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_perfect_attestation / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_miss_attestation / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_invalid_attestation{reason=\"high_inclusion_delay\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_invalid_attestation{reason=\"invalid_head\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_invalid_attestation{reason=\"invalid_target\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_other_validator_balance_invalid_attestation{reason=\"invalid_source\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "💸 Balances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total balance 24h delta",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "(sum(ethereum_validators_monitoring_total_balance_24h_difference{nos_module_id=\"${module_var}\"}) / 10 ^ 9) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "delta"
      }
     ]
    },
    {
     "title": "Average validator balances delta",
     "type": "bargauge",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sort_desc(ethereum_validators_monitoring_validator_balances_delta{nos_module_id=\"${module_var}\"}))",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Number of validators with negative delta",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 78 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_negative_balances_delta{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Total balance of validators with negative delta (ETH)",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 85 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balance_with_negative_balances_delta{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with worst balance delta",
     "type": "table",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_nos_name as Operator,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE\n      val_nos_module_id = '${module_var}' AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var}\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE\n      val_nos_module_id = '${module_var}' AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var} - 6\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      val_nos_module_id = '${module_var}' AND\n      val_nos_id IS NOT NULL AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_stuck = 0 AND\n      epoch > (${epoch_number_var} - 6) AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Operator, Validator\nLIMIT 100",
       "rawQuery": "SELECT\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_nos_name as Operator,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE\n      val_nos_module_id = '1' AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = 216247\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE\n      val_nos_module_id = '1' AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = 216247 - 6\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      val_nos_module_id = '1' AND\n      val_nos_id IS NOT NULL AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_stuck = 0 AND\n      epoch > (216247 - 6) AND epoch <= 216247\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Operator, Validator\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Worst validator balances delta [0.1% percentile]",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 92 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_quantile_001_balances_delta{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "📥 Proposals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed proposals (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  block_to_propose as Block,\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  is_proposer = 1 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  block_proposed = 0 AND\n  (epoch <= ${epoch_number_var} AND epoch >= (${epoch_number_var} - ${epochs_range}))\nORDER BY block_to_propose DESC, Operator, Validator\nLIMIT 1 by epoch, val_id",
       "rawQuery": "SELECT\n  block_to_propose as Block,\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  is_proposer = 1 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  block_proposed = 0 AND\n  (epoch <= 216250 AND epoch >= (216250 - 50))\nORDER BY block_to_propose DESC, Operator, Validator\nLIMIT 1 by epoch, val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with missed proposals",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 100 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_propose{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔄 Sync Committee participation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "User vs Other",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(ethereum_validators_monitoring_user_sync_participation_avg_percent{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "User"
      },
      {
       "expr": "sum(ethereum_validators_monitoring_other_sync_participation_avg_percent) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Bad Sync Committee participation",
     "type": "table",
     "description": "AVERAGE.\n`Bad` is considered when validator's sync is less than chain average value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 88 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    sync_percent as Percent,\n    val_nos_name as Operator,\n    val_id as Validator,\n    val_balance as Balance\nFROM\n    validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  is_sync = 1 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var} AND\n  sync_percent < (${chain_sync_avg_participation} - ${sync_participation_distance_var})\nORDER BY sync_percent, Operator, Validator\nLIMIT 1 by epoch, val_id",
       "rawQuery": "SELECT\n    sync_percent as Percent,\n    val_nos_name as Operator,\n    val_id as Validator,\n    val_balance as Balance\nFROM\n    validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  is_sync = 1 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = 216253 AND\n  sync_percent < (94.451904296875 - 0)\nORDER BY sync_percent, Operator, Validator\nLIMIT 1 by epoch, val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with sync participation less average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 88 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Total balance of validators with sync participation less average (ETH)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 96 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balance_with_sync_participation_less_avg{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "📝 Attestations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validators with MISSED attestation",
     "type": "table",
     "description": "TOP 100",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 91 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  att_happened = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "rawQuery": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  att_happened = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = 216255\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with MISSED attestation",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 91 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_miss_attestation{nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Total balance of validators with MISSED attestation (ETH)",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 99 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balance_miss_attestation{nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with high INCLUSION DELAY attestation",
     "type": "table",
     "description": "TOP 100 (inclusion delay > 1)",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 107 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  att_happened = 1 AND\n  att_inc_delay > 1 AND\n  val_stuck = 0 AND\n  val_nos_id IS NOT NULL AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "rawQuery": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  att_happened = 1 AND\n  att_inc_delay > 1 AND\n  val_stuck = 0 AND\n  val_nos_id IS NOT NULL AND\n  epoch = 216255\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with high attestation INCLUSION DELAY",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 107 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Total balance of validators with high attestation INCLUSION DELAY (ETH)",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 115 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"high_inclusion_delay\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid HEAD",
     "type": "table",
     "description": "TOP 100",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 123 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE \n  val_nos_module_id = '${module_var}' AND\n  att_valid_head = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "rawQuery": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator,\n  val_balance as Balance\nFROM validators_summary\nWHERE \n  val_nos_module_id = '1' AND\n  att_valid_head = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = 216255\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation HEAD",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 123 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Total balance of validators with invalid attestation HEAD (ETH)",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 131 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_balance_invalid_attestation{reason=\"invalid_head\",nos_module_id=\"${module_var}\"} / 10^4) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid TARGET",
     "type": "table",
     "description": "TOP 100",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 139 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\nSELECT\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  att_valid_target = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 100",
       "rawQuery": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  att_valid_target = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = 216256\nORDER BY val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation TARGET",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 139 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_target\", nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validator with invalid SOURCE",
     "type": "table",
     "description": "TOP 100",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 147 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\nSELECT\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  att_valid_source = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "rawQuery": "SELECT\n  val_nos_name as Operator,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  att_valid_source = 0 AND\n  val_nos_id IS NOT NULL AND\n  val_stuck = 0 AND\n  epoch = 216256\nORDER BY val_id\nLIMIT 1 by val_id\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation SOURCE",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 147 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_validator_count_invalid_attestation{reason=\"invalid_source\", nos_module_id=\"${module_var}\"}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔪 Slashed validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slashed validators (User)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    val_nos_name as Operator,\n    val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '${module_var}' AND\n  (val_status == 'active_slashed' OR val_status == 'exited_slashed' OR val_slashed == 1) AND\n  val_nos_id IS NOT NULL\n  AND epoch = ${epoch_number_var}\nORDER by val_id\nLIMIT 1 by val_id",
       "rawQuery": "SELECT\n    val_nos_name as Operator,\n    val_id as Validator\nFROM validators_summary\nWHERE\n  val_nos_module_id = '1' AND\n  (val_status == 'active_slashed' OR val_status == 'exited_slashed' OR val_slashed == 1) AND\n  val_nos_id IS NOT NULL\n  AND epoch = 216259\nORDER by val_id\nLIMIT 1 by val_id",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}